backend:
  name: git-gateway
  branch: main

media_folder: "news/images"
public_folder: "/news/images"

collections:
  - name: "news"
    label: "Știri"
    folder: "news"
    create: true
    extension: "json"
    format: "json"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "Titlu"
        name: "title"
        widget: "string"

      - label: "Data publicării"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DDTHH:mm:ssZ"

      - label: "Categorie"
        name: "category"
        widget: "select"
        options:
          - label: "🏗️ Construim"
            value: "construim"
          - label: "📚 Învățăm"
            value: "invatam"
          - label: "🔬 Cercetăm"
            value: "cercetam"

      - label: "Imagine"
        name: "image"
        widget: "image"
        required: false

      - label: "Cuvinte cheie"
        name: "tags"
        widget: "list"
        required: false

      - label: "Conținut"
        name: "body"
        widget: "markdown"

      - label: "Link articol original"
        name: "source_url"
        widget: "string"
        required: false
